### ISSUE TITLE
nonebot_plugin_auto_teenstudy | 2022-10-13 11:38:56.873534: 错误信息：'ConnectTimeout' object has no attribute 'split'

### ISSUE THREAD

**Issue by gonggonggnog** [ZMXC01/nonebot_plugin_auto_teenstudy#24]
安徽地区提交大学习报错nonebot_plugin_auto_teenstudy | 2022-10-13 11:38:56.873534: 错误信息：'ConnectTimeout' object has no attribute 'split'
用源码提交{'code': 200, 'message': '执行成功'}就能成功，望大佬解答，我的大学习指令是有返回值的，就是提交时候报错

**Comment by SonderZhong** [comment]
已更新，有问题可进交流群询问
