### ISSUE TITLE
apscheduler插件版本问题

### ISSUE THREAD

**Issue by river0Love** [ZMXC01/nonebot_plugin_auto_teenstudy#26]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
nonebot-plugin-auto-teenstudy 0.1.6 requires nonebot-plugin-apscheduler<0.2.0,>=0.1.3, but you have nonebot-plugin-apscheduler 0.2.0 which is incompatible.

请问我将如何安装旧版本插件，或使用何种方法更改

**Comment by 123summertime** [comment]
![无标题](https://user-images.githubusercontent.com/73610948/195995024-97014aba-9fb5-4bb6-b03c-dc85cbef1d40.png)
0.2.0版本可以运行

**Comment by SonderZhong** [comment]
已更新
