### ISSUE TITLE
浙江地区添加报错无nid,看浙江的举例配置里无nid参数，是不是脚本现在没适配好

### ISSUE THREAD

**Issue by hk20203** [ZMXC01/nonebot_plugin_auto_teenstudy#27]

**Comment by hk20203** [comment]
把nid放在json里也是报无nid

**Comment by hk20203** [comment]
自己手动写入json文件，可用

**Comment by SonderZhong** [comment]
浙江地区需要抓取团支部数据，现阶段放弃浙江地区的更新，后续统一使用Web UI 版本更新，如您有兴趣，可移步Web UI版本：https://github.com/ZM25XC/TeenStudy或进交流群进行开发交流
