### ISSUE TITLE
上海地区显示TypeError object has no attribute 'split'

### ISSUE THREAD

**Issue by MrDeemoZe** [ZMXC01/nonebot_plugin_auto_teenstudy#31]
![da75c8ba92b9f2061989eae2f6248a3](https://user-images.githubusercontent.com/93331578/198894054-918da5ee-b319-4433-ac7d-88eb1a78bc2a.jpg)
感觉可能是参数设置错误了
不是很明白cookie和nid是啥
我nid写的是高校系统的N0001

**Comment by yyk725** [comment]
同样是上海，但是报错信息不太一样
![Cache_7889cb9127c124f0](https://user-images.githubusercontent.com/72236930/205670350-54580990-0304-4db8-acbe-3d0eea0ce7a7.jpg)

**Comment by yyk725** [comment]
感觉自己可能抓错包了
不过我的nid是特别长一串：N0004000500091004

**Comment by SonderZhong** [comment]
已更新，有问题可进交流群询问
