### ISSUE TITLE
河南地区换绑后原微信无法登录进去

### ISSUE THREAD

**Issue by Baoer1** [ZMXC01/nonebot_plugin_auto_teenstudy#35]
用另一个微信号新绑定了原来的青年大学习，抓包后能自动完成，但原先的微信号就登不进去了，要怎么办
![HX6A77U0QDO$TJ}2_~44J6K](https://user-images.githubusercontent.com/101307731/203014000-21be355c-d330-44df-8b07-0dfc630d2eaf.jpg)
![mmexport1669022738565](https://user-images.githubusercontent.com/101307731/203014020-047484ac-b15e-41af-8cb8-4490d64116f1.jpg)

**Comment by SonderZhong** [comment]
河南共青团的问题，不是插件的问题
