### ISSUE TITLE
[更新时间]更新时间在周一无法正常更新

### ISSUE THREAD

**Issue by yhzcake** [ZMXC01/nonebot_plugin_auto_teenstudy#37]
我仔细观察了最近的大学习更新时间，发现已经不在周一了，希望能自行设置更新时间或者将更新放置在每一天，更新失败无提示或一周一个提示

**Comment by yhzcake** [comment]
最近每次都是周末自己手动更新的

**Comment by SonderZhong** [comment]
1、寒假即将拉开序幕，请等待，项目在寒假将进行重构
2、各省大学习更新统一以中青在线（每周周末更新）的为准，基本在每周一9点后才更新，请勿手贱在周末使用更新大学习指令进行更新
3、检测大学习是否更新是比对本地数据与中青在线的数据是否一致，如一致则在每周一9点后会提示本周没有大学习
4、提交大学习和自动提交大学习会正常执行

**Comment by yhzcake** [comment]
原来是这样,我机器人卡住然后有一段时间没开,然后周末手动更新的大学习,然后就提交不上了

**Comment by yhzcake** [comment]
原来是这样,我机器人卡住然后有一段时间没开,然后周末手动更新的大学习,然后就提交不上了
