### ISSUE TITLE
无法正常加载，显示无法导入requests

### ISSUE THREAD

**Issue by yyk725** [ZMXC01/nonebot_plugin_auto_teenstudy#38]
File "D:\Yunzai\Yunzai-Bot\plugins\py-plugin\plugins\nonebot_plugin_auto_teenstudy\nonebot_plugin_auto_teenstudy\dxx.py", line 10, in <module>
import requests
ModuleNotFoundError: No module named 'requests'
可是我用pip装过了

**Comment by SonderZhong** [comment]
你使用的环境里没有requests，请检查当前使用的python运行环境中是否有requests库

**Comment by yyk725** [comment]
pip list看过了，有2.28.1的requests

**Comment by SonderZhong** [comment]
是你运行的环境，不是系统里的python环境

**Comment by yyk725** [comment]
欸……不会了啊
我系统里只装了python3.10.1，作者能麻烦教我怎么看吗QwQ

**Comment by yyk725** [comment]
谢谢作者，我解决了
应该在py-plugin根目录执行poetry run pip install requests
谢谢作者的耐心帮助
