### ISSUE TITLE
能否适配nonebot_plugin_apscheduler==0.2.0

### ISSUE THREAD

**Issue by Agnes4m** [ZMXC01/nonebot_plugin_auto_teenstudy#40]
因为更新其他插件时候发现，大多数插件都适配nonebot_plugin_apscheduler==0.2.0了
![image](https://user-images.githubusercontent.com/70925546/206117326-65d4873f-1e8b-48ed-8401-c38b5f9b82b3.png)

**Comment by SonderZhong** [comment]
已更新
